### ISSUE TITLE
copyright and license violation

### ISSUE THREAD

**Issue by nicolaasuni** [paterik/BGBarcodeBundle#12]
This project is using code copied from:
https://github.com/tecnickcom/TCPDF
but all copyright and license terms were removed.
Please immediately delete all the copied code or adapt it to conform the original copyright and license requirements.

Please also note that the code you have copied has now been replaced by another project:
https://github.com/tecnickcom/tc-lib-barcode

Please carefully read the license and act promptly.

**Comment by paterik** [comment]
uhh, okay ... actually this is the first time I ever heard about a license violation issue caused by my bgBarcodeBundle project. this project is uses 98% refactored sources of "tonydspaniard" (https://github.com/tonydspaniard/2D-3D-Barcodes-Generator) interpretation of Dinesh Rabara's MIT-licensed open source version codebase (released 3 years ago). please show me the corresponding license-term violation lines in my code (files/methods). If there is any truth in your accusation I will consider using alternative code or change/extend the base license of my project.

furthermore i've placed all origin authors in every related code lines/methods/classes and refer to every corresponding/known origin codebase!

best regards,

Patrick

**Comment by nicolaasuni** [comment]
Also the "tonydspaniard" code has been copied.
Just have a look at these files to have an idea....
https://github.com/tecnickcom/TCPDF/tree/develop/include/barcodes

**Comment by paterik** [comment]
Hi

okay ... i think we've a problem here ... it seems to be that two identically versions of your tcpdf barcode classes (datamatrix.php, pdf417.php, qrcode.php) existing on github ... my used code based on the MIT licensed version of Dinesh Rabara class files ... MIT means i can improve code base, fix errors, include additional functionality as long as i publish this forked codebase under the same license (MIT) ... i've clearly go this way ... if you are the origin author of this code and contact dinesh rabara and clean up your 2 different ways of licensing your code ... who is the author? you or dinesh? ... what license is currently the valid one? MIT or GNU-LGPL v3? what code can i use ... your "origin" source files or this one here (https://github.com/dineshrabara/barcodeAll/blob/master/src/Datamatrix.php) ... i'm confused

good night,

Patrick

**Comment by nicolaasuni** [comment]
You are basing your code on a non original copy, so you have either delete your project or use the original files with the right license and then apply your changes.
In any case, why don't you just use the new https://github.com/tecnickcom/tc-lib-barcode project instead of trying to patch an old code?

**Comment by paterik** [comment]
I'll patch my project after my vacation on 27th/28th of august but using dinesh rabara's MIT licensed code base https://github.com/dineshrabara/barcodeAll instead of yours ...

**Comment by nicolaasuni** [comment]
I already asked to to take down the https://github.com/dineshrabara/barcodeAll repository.

The options you have to remedy the infringement are:

1. adopt a GNU-LGPLv3 compatible license and replace the infringing files with the original ones, or reinstate the original notices (author, copyright, license);
2. delete the infringing files and use the new external library https://github.com/tecnickcom/tc-lib-barcode (originally based on the same code) - you still need a GNU-LGPLv3 compatible license;
3. take down this project.

**Comment by paterik** [comment]
hi nicolaasuni,

so ... i'm writing this message from my vacation point now ... don't bother me anymore(!) i've made my point clear ... pls inform me about your on-going license state/suite issue/problem with danish's project   "https://github.com/dineshrabara/barcodeAll" by mail. as long as this project exist, i'll use his code! if his projects will be take down - i'll may use your lgpl v3 licensed version!

this issue will be closed now!

and (btw) watch your voice dude - thats very rude and unprofessional behaviour! 

...

**Comment by shangguokan** [comment]
@nicolaasuni i was totally agree with paterik, this project and my project and others's, all these projects "infringement" were issued from Dinesh Rabara's, you'd better contact with him first, because it's upstream.
