### ISSUE TITLE
Generated barcode image is not scannable by barcode scanner

### ISSUE THREAD

**Issue by dbhattacharjee** [paterik/BGBarcodeBundle#13]
Hi ,

We are using your bundle to generate barcode images(PNG) of package's tracking code. 
However generated barcodes are not getting scanned by barcode scanner devices.
For your reference, we have uploaded one image generated by your bundle and another by some third party website. In both cases, "dipanjan" text is used for the input.
Bundle : http://s3-us-west-2.amazonaws.com/ezt-development/uploads/organizations/barcode/dipanjan.png
Third party : http://www.barcodesinc.com/generator/image.php?code=dipanjan&style=197&type=C128B&width=193&height=50&xres=1&font=3

You can notice there are difference in the generated barcode (last three lines are more prominent). In both cases we have used C128B algorithm.

Can you please suggest how we can rectify the issue ?

Thanks,

**Comment by paterik** [comment]
Hi,

i'll take a look into our C128B calculation/rendering code block, check the results and will reply as soon as i got a patch/medecine for this

thank you for sending this issue :)

best regards
Patrick

**Comment by dbhattacharjee** [comment]
Thanks Patrick for quick reply. As of now, I have tried with https://github.com/shangguokan/SGKBarcodeBundle and it is working for me.
