### ISSUE TITLE
Raw HTML barcode not Displaying on PDF File/Printing the page

### ISSUE THREAD

**Issue by TaqiOfficial** [paterik/BGBarcodeBundle#15]
- Issue 1

On a normal webpage the barcode is displaying perfectly, but when i ctrl + P the page, the barcode is not displaying. 

-- Issue 2
When displaying the bar-code as image, then the bar-code image is not displaying on the page. below is the code.
```
  $myBarcode = new barCode();
  $brochuresDir = $this->container->getParameter('kernel.root_dir').'/../web/uploads/barcode/cache';
  $myBarcode->savePath = $brochuresDir;
  $bcPathAbs = $myBarcode->getBarcodePNGPath('796459876', 'EAN13', 1.75, 45);

return $this->render('MISDashboardBundle:DocumentManagement/Dashboard:download_application2.html.twig', array(
                'user'=>$userRepo,
                'barcodePathAndFile' => $this->getBarcodeCachePath($bcPathAbs),
            ));

/**
     * simple cache path returning method (sample cache path: "uploads/barcode/cache" )
     *
     * @param bool $public
     *
     * @return string
     *
     */
    protected function getBarcodeCachePath($public = false)
    {
        return (!$public) ? $this->get('kernel')->getRootDir(). '/../web/uploads/barcode/cache' : '/uploads/barcode/cache';
    }


in the twig file. i had print the variable.
{{ barcodePathAndFile }}
        <br />
        <br />
        <br />
        <img src="{{ barcodePathAndFile }}" alt="barcode" title="my barcode image">
```

> and it only prints the path, not the file `/uploads/barcode/cache `

**Comment by paterik** [comment]
Hi "TaqiOfficial",

I'll check this behaviour as soon as possible and will provide a corresponding update related to your issue. Take note, that we'll working on an upcoming version of this bundle including additional features and code/performance improvements.

Thank your for your report,

best regards
Patrick

**Comment by TaqiOfficial** [comment]
Hi, Petrick

I have solve this issue By Making the Twig Extension for this and a bit configuration for storing bar-code images. Now, don't need to load the barcode from controller, can do this from twig files directly.

**Comment by paterik** [comment]
Hi TaqiOfficial,

thank you for your reply and great ... good idea for solving that problem :)

good day + regards

Patrick
