### ISSUE TITLE
Symfony 3

### ISSUE THREAD

**Issue by vetheslav** [paterik/BGBarcodeBundle#20]
Hello! Can you use this commit https://github.com/austinsk8s/BGBarcodeBundle/commit/f215bd901cbe055c10e632e9b37275c87cdb9608 and update realize to composer?
Thanks.

**Comment by paterik** [comment]
Hi vetheslav, ... Okay I'll update the composer symfony requirements but have to place this change in another major version ... thanx for notification :)

**Comment by vetheslav** [comment]
Thanks, we are waiting :)

**Comment by acidjames** [comment]
+1 👍

**Comment by kalikoweb** [comment]
Hello, we are wating for that, do you know when can be ?

**Comment by paterik** [comment]
version 1.0.0 should be working with the current symfony framework core and legacy versions also now (3.1.n).

**Comment by paterik** [comment]
take note, that this "bundle" is one of my legacy code projects and (really) should be abandoned for a completely refactored/recode using another (new) repository ... I'll try to find some free hours to do this ;) feel free to participate ...

thanx + regards

**Comment by kalikoweb** [comment]
Hey, thank you about that. is error when i update my composer: 

Installation request for bitgrave/barcode-bundle dev-master -> satisfiable by bitgrave/barcode-bundle[dev-master].
    - bitgrave/barcode-bundle dev-master requires php ^5.6 || ^7.0 -> your PHP version (7.0.4-7ubuntu2.1) overridden by "config.platform.php" version (5.5.9) does not satisfy that requirement.

**Comment by paterik** [comment]
Hi @kalikoweb ... your php version should be working now. I've (re)set the compatibility-feature for php 5.5.n into my composer.json

**Comment by kalikoweb** [comment]
Hey @paterik, it's work = ) Thank you so much

**Comment by paterik** [comment]
@kalikoweb ... no thanks to that ... I'm happy that my (legacy) code is working for you now :)
