### ISSUE TITLE
Support text under barcode

### ISSUE THREAD

**Issue by meron1122** [paterik/BGBarcodeBundle#8]
Example:
![2000px-code_128b-2009-06-02 svg](https://cloud.githubusercontent.com/assets/2895090/6428576/739c6e1a-bfa8-11e4-9586-8ab953597198.png)

**Comment by paterik** [comment]
... hmm, ok - nice idea, i'll think about an optional text rendering below barcodes. It will be a feature after refactoring this library :)

**Comment by meron1122** [comment]
I wait lovely :)
